services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html/
    ports:
      - ${PORT}:80
    networks:
      - attendance-network
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - attendance-network
    volumes:
      - db-data:/var/lib/mysql
networks:
  attendance-network:
    driver: bridge
volumes:
  db-data:
    driver: local
  